FROM docker:dind

# install basic tools
RUN apk add --update make g++ nodejs npm git python3 curl gcompat tini

# install git-credential-manager
RUN curl -L https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.1.2/gcm-linux_amd64.2.1.2.tar.gz -o /tmp/gcm.tar.gz && \
    tar -xvf /tmp/gcm.tar.gz -C /usr/bin && \
    rm /tmp/gcm.tar.gz && \
    echo "export GCM_CREDENTIAL_STORE=plaintext" > /root/.profile

# add code-oss package
COPY code-oss/vscode-reh-web-linux-x64 /code-oss
RUN cd /code-oss && npm i --legacy-peer-deps

COPY dist /fullstacked
RUN cd /fullstacked && npm i node-pty

# make /home the user root folder
RUN sed -i 's/\/root:\/bin\/ash/\/home:\/bin\/ash/g' /etc/passwd

WORKDIR /home

RUN rm -rf /home/dockremap && \
    npm config set prefix '/home/.npm/' && \
    echo "export PATH=\$PATH:/home/.npm/bin" >> /root/.profile && \
    echo "#!/bin/sh" >> /bin/code && \
    echo "echo CODE#\`pwd\`" >> /bin/code && \
    chmod +x /bin/code && \
    echo "#!/bin/sh" >> /bin/open && \
    echo "echo OPEN#\`pwd\`" >> /bin/open && \
    chmod +x /bin/open && \
    mkdir -p /home/.npm/lib && \
    git-credential-manager configure

CMD ["tini", "--", "/bin/sh", "-c", "source /root/.profile && (/usr/local/bin/dockerd-entrypoint.sh & node /code-oss/out/server-main.js --without-connection-token --host 0.0.0.0 --port 8888 & DOCKER_HOST=\"\" CLIENT_DIR=/fullstacked/client node /fullstacked/server/index.mjs)"]
